
//
export const FETCH_ACCOUNT_INFO_SUCCESS = "FETCH_ACCOUNT_INFO_SUCCESS";
export const FETCH_ACCOUNT_INFO_FAILED = "FETCH_ACCOUNT_INFO_FAILED";

//
export const FETCH_LOTTERY_INFO_SUCCESS = "FETCH_LOTTERY_INFO_SUCCESS";
export const FETCH_LOTTERY_INFO_FAILED = "FETCH_LOTTERY_INFO_FAILED";