//
// LAYOUT
//

// FETCH WEB3 NETWORK
export const FETCH_NETWORK_SUCCESS = "FETCH_NETWORK_SUCCESS";
export const FETCH_NETWORK_FAILED = "FETCH_NETWORK_FAILED";

// FETCH ACCOUNT ADDRESS
export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESS_FAILED = "FETCH_ADDRESS_FAILED";

// FETCH ACCOUNT ETHER BALANCE
export const FETCH_ETH_BALANCE_SUCCESS = "FETCH_ETH_BALANCE_SUCCESS";
export const FETCH_ETH_BALANCE_FAILED = "FETCH_ETH_BALANCE_FAILED";

// FETCH ACCOUNT DAI BALANCE
export const FETCH_DAI_BALANCE_SUCCESS = "FETCH_DAI_BALANCE_SUCCESS";
export const FETCH_DAI_BALANCE_FAILED = "FETCH_DAI_BALANCE_FAILED";

//
// LOTTERY FUNCTIONS
//

// FETCH POOL STATE
export const FETCH_POOL_STATE_SUCCESS = "FETCH_POOL_STATE_SUCCESS";
export const FETCH_POOL_STATE_FAILED = "FETCH_POOL_STATE_FAILED";

// FETCH TIME TO STOP ALLOWING NEW ENTRIES
export const FETCH_TIME_STOP_SPLASH_SUCCESS = "FETCH_TIME_STOP_SPLASH_SUCCESS";
export const FETCH_TIME_STOP_SPLASH_FAILED = "FETCH_TIME_STOP_SPLASH_FAILED";

// FETCH CURRENT POOL SIZE
export const FETCH_CURRENT_POOL_SUCCESS = "FETCH_CURRENT_POOL_SUCCESS";
export const FETCH_CURRENT_POOL_FAILED = "FETCH_CURRENT_POOL_FAILED";

// FETCH THE CURRENT USER'S DEPOSIT IN THE POOL
export const FETCH_DEPOSIT_SUCCESS = "FETCH_DEPOSIT_SUCCESS";
export const FETCH_DEPOSIT_FAILED = "FETCH_DEPOSIT_FAILED";

// FETCH THE CURRENT APR FOR THE POOL SAVING
export const FETCH_CURRENT_APR_SUCCESS = "FETCH_CURRENT_APR_SUCCESS";
export const FETCH_CURRENT_APR_FAILED = "FETCH_CURRENT_APR_FAILED";

// FETCH NUMBER OF ENTRANTS
export const FETCH_ENTRANTS_SUCCESS = "FETCH_ENTRANTS_SUCCESS";
export const FETCH_ENTRANTS_FAILED = "FETCH_ENTRANTS_FAILED";

// FETCH ENTRIES & SAVINGS
export const FETCH_ENTRIES_SUCCESS = "FETCH_ENTRIES_SUCCESS";
export const FETCH_ENTRIES_FAILED = "FETCH_ENTRIES_FAILED";

// CHECK DAI ALLOWANCE 
export const CHECK_DAI_ALLOWANCE_SUCCESS = "CHECK_DAI_ALLOWANCE_SUCCESS";
export const CHECK_DAI_ALLOWANCE_FAILED = "CHECK_DAI_ALLOWANCE_FAILED";

// APPROVE DAI FOR TRANSFER
export const APPROVE_DAI_SUCCESS = "APPROVE_DAI_SUCCESS";
export const APPROVE_DAI_FAILED = "APPROVE_DAI_FAILED";

// ENTER THE POOL (SPLASH ETH)
export const ENTER_ETH_POOL_SUCCESS = "ENTER_ETH_POOL_SUCCESS";
export const ENTER_ETH_POOL_FAILED = "ENTER_ETH_POOL_FAILED";

// ENTER THE POOL (SPLASH DAI)
export const ENTER_DAI_POOL_SUCCESS = "ENTER_DAI_POOL_SUCCESS";
export const ENTER_DAI_POOL_FAILED = "ENTER_DAI_POOL_FAILED";

// WITHDRAW ETHER
export const WITHDRAW_ETHER_SUCCESS = "WITHDRAW_ETHER_SUCCESS";
export const WITHDRAW_ETHER_FAILED = "WITHDRAW_ETHER_FAILED";

// WITHDRAW DAI
export const WITHDRAW_DAI_SUCCESS = "WITHDRAW_DAI_SUCCESS";
export const WITHDRAW_DAI_FAILED = "WITHDRAW_DAI_FAILED";

//
// MANAGE LOTTERY
//

// FETCH CONTRACT MANAGER
export const FETCH_MANAGER_SUCCESS = "FETCH_MANAGER_SUCCESS";
export const FETCH_MANAGER_FAILED = "FETCH_MANAGER_FAILED";

// PICK WINNER
export const PICK_WINNER_SUCCESS = "PICK_WINNER_SUCCESS";
export const PICK_WINNER_FAILED = "PICK_WINNER_FAILED";

// SUPPLY COMPOUND FINANCE
export const EARN_INTEREST_SUCCESS = "EARN_INTEREST_SUCCESS";
export const EARN_INTEREST_FAILED = "EARN_INTEREST_FAILED";

// GET SUPPLY BALANCE FROM COMPOUND FINANCE
export const FETCH_COMPOUND_SUPPLY_BALANCE_SUCCESS = "FETCH_COMPOUND_SUPPLY_BALANCE_SUCCESS";
export const FETCH_COMPOUND_SUPPLY_BALANCE_FAILED = "FETCH_COMPOUND_SUPPLY_BALANCE_FAILED";

// WITHDRAW FROM COMPOUND FINANCE
export const WITHDRAW_FROM_COMPOUND_SUCCESS = "WITHDRAW_FROM_COMPOUND_SUCCESS";
export const WITHDRAW_FROM_COMPOUND_FAILED = "WITHDRAW_FROM_COMPOUND_FAILED";

// RESTART POOL
export const RESTART_POOL_SUCCESS = "RESTART_POOL_SUCCESS";
export const RESTART_POOL_FAILED = "RESTART_POOL_FAILED";

// CREATE POOL
export const CREATE_POOL_SUCCESS = "CREATE_POOL_SUCCESS";
export const CREATE_POOL_FAILED = "CREATE_POOL_FAILED";
