
// FETCH ACCOUNT ADDRESS
export const FETCH_ADDRESS_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESS_FAILED = "FETCH_ADDRESS_FAILED";

// FETCH ACCOUNT BALANCE
export const FETCH_BALANCE_SUCCESS = "FETCH_BALANCE_SUCCESS";
export const FETCH_BALANCE_FAILED = "FETCH_BALANCE_FAILED";

// FETCH WEB3 NETWORK
export const FETCH_NETWORK_SUCCESS = "FETCH_NETWORK_SUCCESS";
export const FETCH_NETWORK_FAILED = "FETCH_NETWORK_FAILED";

// FETCH POOL STATE
export const FETCH_POOL_STATE_SUCCESS = "FETCH_POOL_STATE_SUCCESS";
export const FETCH_POOL_STATE_FAILED = "FETCH_POOL_STATE_FAILED";

// FETCH TIME TO STOP ALLOWING NEW ENTRIES
export const FETCH_TIME_STOP_SPLASH_SUCCESS = "FETCH_TIME_STOP_SPLASH_SUCCESS";
export const FETCH_TIME_STOP_SPLASH_FAILED = "FETCH_TIME_STOP_SPLASH_FAILED";

// FETCH CURRENT POOL SIZE
export const FETCH_CURRENT_POOL_SUCCESS = "FETCH_CURRENT_POOL_SUCCESS";
export const FETCH_CURRENT_POOL_FAILED = "FETCH_CURRENT_POOL_FAILED";

// ENTER THE POOL (SPLASH)
export const ENTER_POOL_SUCCESS = "ENTER_POOL_SUCCESS";
export const ENTER_POOL_FAILED = "ENTER_POOL_FAILED";

// FETCH ANY CURRENT ENTRY IN THE POOL
export const FETCH_ENTRIES_SUCCESS = "FETCH_ENTRIES_SUCCESS";
export const FETCH_ENTRIES_FAILED = "FETCH_ENTRIES_FAILED";

// FETCH THE CURRENT APR FOR THE POOL SAVING
export const FETCH_CURRENT_APR_SUCCESS = "FETCH_CURRENT_APR_SUCCESS";
export const FETCH_CURRENT_APR_FAILED = "FETCH_CURRENT_APR_FAILED";

